### ISSUE TITLE
Running oc create -f olm/kubefed.yaml does not create the pods under namespace "test-namespace"

### ISSUE THREAD

**Issue by bryantson** [openshift/federation-dev#127]
Running oc create -f olm/kubefed.yaml does not create the pods under namespace "test-namespace". 

This just ends up creating the namespace "test-namespace" and operatorgroup, and subscriptions.

**Comment by sreekanth-ragi** [comment]
I'm facing the same issue, my env is
Openshift 3.11 running as a single node cluster

**Comment by sreekanth-ragi** [comment]
Any update on the below issue or pointers on where to look for the issue?
