### ISSUE TITLE
lab 5, add cleanup notes

### ISSUE THREAD

**Issue by scollier** [openshift/federation-dev#63]
so, if someone has a problem with lab 5, how do they clean it up?  lab 4 has instructions at the end of the page.  Should we create a single page with headers on it like: "Lab 4 cleanup", "Lab 5 Cleanup", "Lab 6 CLeanup",  and link to those headers at the bottom of each lab? that would be a consistent experience and allow people to start over at that lab if they need to.

**Comment by cooktheryan** [comment]
I like the link to the single page. it would make things easier and we can link within the lab that says something like if things are going wrong do this to reset

**Comment by scollier** [comment]
@cooktheryan added #65

**Comment by scollier** [comment]
Merged in.   Just need to add instructions for lab 5 and 6 now.

**Comment by scollier** [comment]
https://github.com/openshift/federation-dev/blob/master/labs/cleanup-instructions.md

**Comment by mvazquezc** [comment]
Added a note at the end of lab5.
